function DrawTexture(dim,p0,alpha,img)
%
% G. Antonelli, Simurv 4.0, 2013
% http://www.eng.docente.unicas.it/gianluca_antonelli/simurv

I = imread(img);

surface('XData',[p0(1) p0(1)+dim(1); p0(1) p0(1)+dim(1)],...
    'YData',[p0(2) p0(2); p0(2)+dim(2) p0(2)+dim(2)],...
    'ZData',[p0(3) p0(3); p0(3) p0(3)],...
    'CData',flipdim(I,1),...
    'FaceColor','texturemap','EdgeColor','none',...
    'facealpha',alpha);